# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created: Mon Nov  9 14:19:19 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 255)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt1 = QtGui.QPushButton(self.centralwidget)
        self.bt1.setGeometry(QtCore.QRect(20, 120, 92, 27))
        self.bt1.setObjectName("bt1")
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 501, 31))
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.bt2 = QtGui.QPushButton(self.centralwidget)
        self.bt2.setGeometry(QtCore.QRect(130, 120, 92, 27))
        self.bt2.setObjectName("bt2")
        self.bt3 = QtGui.QPushButton(self.centralwidget)
        self.bt3.setGeometry(QtCore.QRect(240, 120, 92, 27))
        self.bt3.setObjectName("bt3")
        self.bt4 = QtGui.QPushButton(self.centralwidget)
        self.bt4.setGeometry(QtCore.QRect(20, 90, 92, 27))
        self.bt4.setObjectName("bt4")
        self.bt5 = QtGui.QPushButton(self.centralwidget)
        self.bt5.setGeometry(QtCore.QRect(130, 90, 92, 27))
        self.bt5.setObjectName("bt5")
        self.bt6 = QtGui.QPushButton(self.centralwidget)
        self.bt6.setGeometry(QtCore.QRect(240, 90, 92, 27))
        self.bt6.setObjectName("bt6")
        self.bt7 = QtGui.QPushButton(self.centralwidget)
        self.bt7.setGeometry(QtCore.QRect(20, 60, 92, 27))
        self.bt7.setObjectName("bt7")
        self.bt8 = QtGui.QPushButton(self.centralwidget)
        self.bt8.setGeometry(QtCore.QRect(130, 60, 92, 27))
        self.bt8.setObjectName("bt8")
        self.bt9 = QtGui.QPushButton(self.centralwidget)
        self.bt9.setGeometry(QtCore.QRect(240, 60, 92, 27))
        self.bt9.setObjectName("bt9")
        self.btdiv = QtGui.QPushButton(self.centralwidget)
        self.btdiv.setGeometry(QtCore.QRect(340, 60, 92, 27))
        self.btdiv.setObjectName("btdiv")
        self.btmult = QtGui.QPushButton(self.centralwidget)
        self.btmult.setGeometry(QtCore.QRect(340, 90, 92, 27))
        self.btmult.setObjectName("btmult")
        self.btminus = QtGui.QPushButton(self.centralwidget)
        self.btminus.setGeometry(QtCore.QRect(340, 120, 92, 27))
        self.btminus.setObjectName("btminus")
        self.bt0 = QtGui.QPushButton(self.centralwidget)
        self.bt0.setGeometry(QtCore.QRect(20, 150, 201, 27))
        self.bt0.setObjectName("bt0")
        self.btdot = QtGui.QPushButton(self.centralwidget)
        self.btdot.setGeometry(QtCore.QRect(240, 150, 92, 27))
        self.btdot.setObjectName("btdot")
        self.btplus = QtGui.QPushButton(self.centralwidget)
        self.btplus.setGeometry(QtCore.QRect(340, 150, 92, 27))
        self.btplus.setObjectName("btplus")
        self.btclear = QtGui.QPushButton(self.centralwidget)
        self.btclear.setGeometry(QtCore.QRect(440, 60, 91, 51))
        self.btclear.setObjectName("btclear")
        self.bteq = QtGui.QPushButton(self.centralwidget)
        self.bteq.setGeometry(QtCore.QRect(440, 120, 92, 61))
        self.bteq.setObjectName("bteq")
        self.checkbox = QtGui.QCheckBox(self.centralwidget)
        self.checkbox.setGeometry(QtCore.QRect(240, 190, 231, 22))
        self.checkbox.setObjectName("checkbox")
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(140, 190, 55, 27))
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 190, 101, 17))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.bt1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.bt2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.bt3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.bt4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.bt5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.bt6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.bt7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.bt8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.bt9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btdiv.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.btmult.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.btminus.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.bt0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btdot.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.btplus.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btclear.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.bteq.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox.setText(QtGui.QApplication.translate("MainWindow", "Display Thousands\' Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Decimal Digit", None, QtGui.QApplication.UnicodeUTF8))

